# Generated by Django 4.2.5 on 2023-11-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='variant',
            new_name='product_name',
        ),
    ]
