# Generated by Django 4.2.5 on 2023-11-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
